'use strict';
const el=id=>document.getElementById(id), token=document.querySelector('meta[name=csrf-token]').content;
let cases=[],current=null;
const labels={supported:'证据支持该候选',not_supported:'独立样本未支持该候选',inconclusive:'证据仍不确定',insufficient_budget:'预算不足，未执行',no_candidate:'尚无候选可确认',cancelled:'已取消',environment_error:'执行错误，保留已有证据',improved:'该案例支持改善',regressed:'该案例出现退化'};
function status(text,error=false){el('status').textContent=text;el('status').classList.toggle('error',error);}
async function api(path,body){const response=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-ReplayHarbor-Token':token},body:JSON.stringify(body)});const value=await response.json();if(!response.ok)throw new Error(value.error||'请求未完成');return value;}
function setCase(){const item=cases.find(c=>c.id===el('task').value);el('goal').textContent=item?.goal||'';el('repair').replaceChildren(new Option('暂不比较',''));for(const r of item?.repairs||[])el('repair').add(new Option(r,r));}
function render(report,title){
 if(!report||!Array.isArray(report.prefixes)||report.prefixes.length>1000||!report.prefixes.every(r=>Number.isInteger(r.prefix)&&Number.isInteger(r.n)&&r.n>=0&&(r.failure_rate===null||Number.isFinite(r.failure_rate))&&Array.isArray(r.descriptive_interval)&&r.descriptive_interval.length===2))throw new Error('报告格式不符合 ReplayHarbor 前缀证据格式');
 el('model-results').hidden=true;el('results').hidden=false;el('result-title').textContent=title;
 el('candidate').textContent=report.candidate_prefix??'未定位';el('coverage').textContent=Number.isFinite(report.coverage)?(report.coverage*100).toFixed(0)+'%':'—';el('attempts').textContent=report.total_attempts??report.attempts??'—';
 el('prefix-map').replaceChildren();el('prefix-rows').replaceChildren();
 for(const row of report.prefixes){const block=document.createElement('div');block.className='prefix'+(row.n?' covered':'');block.textContent=row.prefix;block.title=`前缀 ${row.prefix}：${row.n} 次复验`;el('prefix-map').append(block);const tr=document.createElement('tr');for(const text of [row.prefix,row.n,row.failure_rate===null?'未覆盖':(row.failure_rate*100).toFixed(1)+'%',row.descriptive_interval.map(v=>Number(v).toFixed(3)).join(' – ')]){const td=document.createElement('td');td.textContent=text;tr.append(td);}el('prefix-rows').append(tr);}
 el('confirmation').textContent=labels[report.confirmation?.status]||'未运行';el('revision').textContent=labels[report.revision?.status]||'未运行';
 const missing=report.untested_prefixes?.length||0;
 el('next-action').textContent=missing?`还有 ${missing} 个前缀未覆盖。增加探索预算后，再安排候选确认。`:report.confirmation?.status==='supported'?'检查证据覆盖与适用范围，选择修订并验证其效果。':report.candidate_prefix!=null?'候选已出现。可使用独立样本确认，保留探索与确认之间的区别。':'当前没有定位到候选。保留本次记录，检查任务判据与复现条件。';
 el('raw').textContent=JSON.stringify(report,null,2);
}
el('task').addEventListener('change',setCase);
el('run-form').addEventListener('submit',async event=>{event.preventDefault();el('run').disabled=true;el('cancel').disabled=false;el('download').hidden=true;status('正在执行本地模拟复验…');try{const job=await api('/api/jobs',{task:el('task').value,budget:Number(el('budget').value),strategy:el('strategy').value,confirm:el('confirm').checked,repair:el('repair').value});current=job.id;while(current===job.id){const value=await api('/api/jobs/'+job.id);if(value.status!=='running'){if(value.status==='error')throw new Error(value.error);render(value.report,value.task);el('download').href='/api/jobs/'+job.id+'/bundle';const cancelled=value.report.stop_reason==='cancelled'||value.report.confirmation?.status==='cancelled'||value.report.revision?.status==='cancelled';el('download').hidden=cancelled;status(cancelled?'已取消，已有证据保留供本地检查。完整运行后可导出可复算问题包。':'复验完成。检查覆盖范围和结论，再导出问题包。');break;}await new Promise(resolve=>setTimeout(resolve,200));}}catch(error){status(error.message,true);}finally{el('run').disabled=false;el('cancel').disabled=true;current=null;}});
el('cancel').addEventListener('click',async()=>{try{if(current){await api('/api/jobs/'+current+'/cancel',{});status('已请求取消，将保留完成的证据。');}}catch(error){status(error.message,true);}});
el('import-file').addEventListener('change',async event=>{el('download').hidden=true;try{const file=event.target.files[0];if(!file)return;if(file.size>2*1024*1024)throw new Error('报告超过 2 MB，请使用较小的脱敏报告');const text=await file.text();if(/\bsk-[A-Za-z0-9_-]{20,}/.test(text))throw new Error('报告包含疑似凭据，请先脱敏');const report=JSON.parse(text);render(report.diagnosis||report,'导入证据 · '+file.name);status('只读导入完成；尚未验证来源、哈希或复算一致性。');}catch(error){status(error.message,true);}finally{event.target.value='';}});
el('model-summary').addEventListener('click',async()=>{try{const data=await api('/api/model-summary');el('results').hidden=true;el('model-results').hidden=false;el('download').hidden=true;el('result-title').textContent='真实模型接入回归';const table=document.createElement('table');for(const values of [['契约','调用次数','续跑成功/总数','估算 USD'],...(data.runs||[]).map(r=>[r.contract,r.calls,`${r.replay_successes}/${r.replay_count}`,Number(r.estimated_usd).toFixed(6)])]){const tr=document.createElement('tr');for(const value of values){const td=document.createElement('td');td.textContent=value;tr.append(td);}table.append(tr);}el('model-table').replaceChildren(table);const control=document.createElement('table');for(const values of [['条件','任务成功/总数'],...(data.controlled_failure?.conditions||[]).map(r=>[({normal:'正常反馈',corrupted_observation:'错误时区反馈',rollback:'恢复并重新澄清'})[r.condition]||r.condition,`${r.successes}/${r.total}`])]){const tr=document.createElement('tr');for(const value of values){const td=document.createElement('td');td.textContent=value;tr.append(td);}control.append(tr);}el('control-table').replaceChildren(control);status('显示已完成的真实实验，本次查看不调用模型。');}catch(error){status(error.message,true);}});
api('/api/cases').then(data=>{cases=data;for(const c of cases)el('task').add(new Option(c.id,c.id));setCase();}).catch(error=>status(error.message,true));
